# Generated by Django 5.0.6 on 2024-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='permis_conduire',
            field=models.FileField(blank=True, null=True, upload_to='permis_conduire/'),
        ),
    ]
