# Generated by Django 5.0.6 on 2024-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajet', '0002_alter_trajet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='nbPersonnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
