# Generated by Django 5.0.6 on 2024-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('trajet', '0003_trajet_nbpersonnes_alter_trajet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='passagers',
            field=models.ManyToManyField(blank=True, related_name='trajets_passager', to='client.client'),
        ),
    ]
