# Generated by Django 5.0.6 on 2024-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('idVisiteur', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomAleatoire', models.CharField(max_length=100)),
            ],
        ),
    ]
