# Generated by Django 5.0.6 on 2024-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomAdmin', models.CharField(max_length=100)),
                ('emailAdmin', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
