# Generated by Django 5.0.6 on 2024-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='password',
            field=models.CharField(default='defaultAdminPass', max_length=128),
        ),
    ]
